name: 'dbt_tpch'
version: '1.0.0'
config-version: 2

profile: 'dbt_tpch' # Match this in your ~/.dbt/profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_tpch:
    # Bronze Layer (Staging) -> Schema: dbt_yourname_stg
    staging:
      +materialized: view
      +schema: stg
    
    # Silver Layer (Intermediate) -> Schema: dbt_yourname_int
    intermediate:
      +materialized: ephemeral
      +schema: int
    
    # Gold Layer (Marts) -> Schema: dbt_yourname_marts
    marts:
      +materialized: table
      +schema: marts